# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'imitateJK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for imitateJK

pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit'
pod 'YYModel'
pod 'MJRefresh'
pod 'SVProgressHUD'

end
